Repository fga-eps-mds/2023-1-CAPJu-Front, pull requests merged in 2023-05, with the labels that each got.

#7 (fga-eps-mds/2023-1-CAPJu-Doc#52) - Atualiza template de pull request
  .github/pull_request_template.md
Labels: documentation, frontend

#8 Página de etapas
  src/pages/Stages/CreationModal/index.tsx
  src/pages/Stages/ExclusionModal/index.tsx
  src/pages/Stages/index.tsx
  src/routes/private.tsx
  src/services/index.ts
  src/services/stages/index.ts
  src/types/global.d.ts
Labels: frontend

#10 Criar pagina de processos
  src/layouts/Private.tsx
  src/pages/Processes/CreationModal/index.tsx
  src/pages/Processes/EditModal/index.tsx
  src/pages/Processes/ExclusionModal/index.tsx
  src/pages/Processes/ProcessDetail/index.tsx
  src/pages/Processes/index.tsx
  src/pages/Stages/CreationModal/index.tsx
  src/routes/private.tsx
  src/services/flows/index.ts
  src/services/index.ts
  src/services/priorities/index.ts
  src/services/processes/index.tsx
  src/types/global.d.ts
Labels: frontend

#22 ENHANCEMENT: Melhorias e correções de bugs
  src/components/NavigationTabs/index.tsx
  src/components/PageSkeleton/index.tsx
  src/components/RequireAuth/index.tsx
  src/pages/Login/index.tsx
  src/pages/ProfilesManager/DeletionModal/index.tsx
  src/pages/ProfilesManager/Profiles/EditionModal/index.tsx
  src/pages/ProfilesManager/Profiles/ViewModal/index.tsx
  src/pages/ProfilesManager/Profiles/index.tsx
  src/pages/ProfilesManager/Requests/ViewModal/index.tsx
  src/pages/ProfilesManager/Requests/index.tsx
  src/pages/ProfilesManager/index.tsx
  src/pages/Signup/index.tsx
  src/pages/Units/EditionModal/index.tsx
  src/pages/Units/index.tsx
  src/pages/Users/DeletionModal/index.tsx
  src/pages/Users/EditionModal/index.tsx
  src/services/units/index.ts
  src/services/user/index.ts
  src/utils/permissions.ts
Labels: bug, enhancement
