Repository fga-eps-mds/2023-1-CAPJu-Front, pull requests merged in 2023-06, with the labels that each got.

#24 Diretores devem poder ver outros diretores na aba de cadastro
  src/pages/ProfilesManager/Profiles/index.tsx
  src/pages/ProfilesManager/Requests/index.tsx
  yarn.lock
Labels: bug

#19 Início de processo
  src/components/Flow/index.tsx
  src/pages/Processes/CreationModal/index.tsx
  src/pages/Processes/EditionModal/index.tsx
  src/pages/ViewProcess/index.tsx
  src/services/processes/index.ts
Labels: frontend

#32 Corrige configuração de testes e cobertura
  .github/workflows/ci.yml
  vitest.config.ts
Labels: devops
